blog/urls.py
from django.urls import path
from . import views

urlpatterns = [ #IP주소/blog/
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('category/<str:slug>/', views.category_page), # IP주소/blog/category/slug/
    path('tag/<str:slug>/', views.tag_page), # IP주소/blog/tag/slug/
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),

    # path('', views.index), #IP/blog/ 블로그 앱 밑에 있는 views로 가겠다
    # path('<int:pk>/', views.single_post_page)
]

myPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from blog import views

router = routers.DefaultRouter()
router.register(r'tests', views.postViewSet)

urlpatterns = [ #ip주소/
    path('admin/', admin.site.urls), #IP주소/admin/ 주소로 갔을 때 처리해 줄 수 있는 것을 보여 줌
    path('blog/', include('blog.urls')), # IP주소/blog 이런 형태의 url
    path('', include('single_pages.urls')), #ip주소/
    path('accounts/', include('allauth.urls')),
    path('drf/', include(router.urls))
] # 사용자가 사용하는 url, 뒤에가 url 처리해 주는 값

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#스트링은 +=가 추가하는 거임 뒤에다 연결

blog/models.py
import os

from django.db import models
from django.contrib.auth.models import User # 다대일 관계

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    # 카테고리 복수를 이렇게 정의 하겠다
    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model): #class의 이름이 table 이름
    title = models.CharField(max_length=30) #제목
    hook_text = models.CharField(max_length=100, blank=True) #글자 수 제한 있음 / content 내용 일부 미리 보기
    content = models.TextField() #작성 내용(제한 없음)

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True) # 연도/월/일 %Y=2022 %y=22로 표현
    #blank 비어 있어도 괜찮다
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True) #작성 시간
    updated_at = models.DateTimeField(auto_now=True)

    # 다대일 관계 -> 작성자
    # 마이그레이션시 1, 1 선택
    # null = True 해당 필드 값 공란이어도 o
    # on_delete => 탈퇴하면 내용 같이 사라짐 models.CASCADE /// SET_NULL 삭제되면 그냥 NULL로 설정
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    # null, blank 공란 허용
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True) # 필드에 null은 true 이미 포함 on_delete도 이미 포함

    def __str__(self):
        return f'[{self.pk}]{self.title}:{self.author}  :  {self.created_at}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1] #a.txt -> a txt (-1은 의미적으로 가장 마지막을 가리킴)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return "https://dummyimage.com/50x50/ced4da/6c757d.jpg"

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return "https://dummyimage.com/50x50/ced4da/6c757d.jpg"

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Post, Category, Tag, Comment
from .forms import CommentForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from django.db.models import Q
from rest_framework import viewsets
from .serializers import postSerializer

class postViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = postSerializer

# Create your views here.
#view에서 사용자 요구 처리

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str = tags_str.replace(',', ';')  # ,도 ;로 바꿔 주도록
            tags_list = tags_str.split(';')  # 단어 단위로 배열 형태로 저장
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)

        return response
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)
        context['categories'] = Category.objects.all()  # 따옴표 안에 있는 걸 변수로, view로 전달한다
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    # 모델명_form.html

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        # 폼 열 때 이 폼이 유효한가? 유저 체크
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or self.request.user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str = tags_str.replace(',', ';')  # ,도 ;로 바꿔 주도록
                tags_list = tags_str.split(';')  # 단어 단위로 배열 형태로 저장
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)

            return response
        else:
            return redirect('/blog/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostCreate, self).get_context_data()
        context['categories'] = Category.objects.all()  # 따옴표 안에 있는 걸 변수로, view로 전달한다
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context

class PostList(ListView):
    model = Post
    ordering = '-pk' #데이터 많이 들어가서 정렬 필요 밑에 상세페이지는 정렬 필요 x
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all() # 따옴표 안에 있는 걸 변수로, view로 전달한다
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context
    #템플릿은 모델명_list.html: post_list.html
    #매개변수 모델명_list : post_list 라고 하는 것이 전달됨

class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context

class PostDetail(DetailView):
    model = Post
    # 템플릿은 모델명_detail.html: post_detail.html
    #매개변수 모델명 : post 라는 것을 통해 전달해 줌

    # CBV에서 추가로 넘기고 싶은 인자 있을 때 사용
    # 특정 조건 레코드만 필터링 할 때 사용
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()  # 따옴표 안에 있는 걸 변수로, view로 전달한다
        context['no_category_post_count'] = Post.objects.filter(category=None).count() # category = None인 포스트만 필터링
        context['comment_form'] = CommentForm
        return context

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else: # GET
                return redirect(post.get_absolute_url())
        else:
            raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
    # 템플릿 : comment_form

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
    return render(request, 'blog/post_list.html', {
        'category' : category,
        'post_list' : post_list,
        'categories' : Category.objects.all(),
        'no_category_post_count' : Post.objects.filter(category=None).count
    })

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    return render(request, 'blog/post_list.html', {
        'tag' : tag,
        'post_list' : post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count
    })



# def index(request):
#     posts = Post.objects.all().order_by('-pk') # 정렬해 주는 명렁어 'pk'는 1 2 3으로 정렬
#     return render(request, 'blog/index.html', {'posts': posts})
#
# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk) #오른쪽은 전달받은 pk
#     return render(request, 'blog/single_post_page.html', {'post': post})
#     #오른쪽에 있는 게 내가 선언해 준 거, 왼쪽은 템플릿에서 전달받는 인수 값

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block head_title %}Blog{% endblock %}</title>
  <link href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
<!--    screen 화면에만 적용하겠다-->
<!--  <script src="js/what_time_is_it.js" type="text/javascript"></script>-->
  <script src="https://kit.fontawesome.com/fe8fadb9a8.js" crossorigin="anonymous"></script>
</head>
<body>
<!--포함하고 싶은 템플릿-->
   {% include 'blog/navbar.html' %}
<!--   include = copy&paste-->
   <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-9" id="main-area">
        {% block main_area %}
          {% endblock %}
      </div>
      <div class="col-md-4 col-lg-3">
        {% include 'blog/sidebar.html' %}
      </div>
    </div>
   </div>
<!--포함하고 싶은 템플릿-->
    {% include 'blog/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Edit Comment</h1>
  <hr/>
  <form method="post" id="comment-form">
  {% csrf_token %}
      {{form | crispy }}
      <br/>
      <button type="submit" class="btn btn-primary float-right">
        Submit
      </button>
  </form>
{% endblock %}

blog/templates/blog/footer.html
  <!-- Footer-->
  <footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; InternetPrograming 2022</p></div>
  </footer>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    {% for p in posts %}
        <h2> <a href="{{p.get_absolute_url}}">{{ p.title }}</a> </h2>
        <h3>{{ p.created_at }}</h3>
        <p> {{ p.content }} </p>
    {% endfor %}
</body>
</html>

blog/templates/blog/navbar.html
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">InternetPrograming</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog/">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about_me/">About me</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {% if user.socialaccount_set.all.0.get_avatar_url %}
              <img class="rounded-circle mr-3" src="{{user.socialaccount_set.all.0.get_avatar_url}}" width="25px" />
              {% else %}
              <img class="rounded-circle mr-3" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" width="25px" />
              {% endif %}
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/accounts/logout/">LogOut</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">LogIn</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- Modal -->
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-right-to-bracket"></i> LogIn</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-6">
              <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% provider_login_url 'google' %}"><i class="fa-brands fa-google"></i> LogIn with Google</a>
              <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/"><i class="fa-regular fa-envelope"></i> LogIn with Email</a>
            </div>
            <div class="col-6">
              <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup/"><i class="fa-regular fa-envelope"></i> SignUp with Email</a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
      </div>
    </div>
  </div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{post.title}} - Blog
{% endblock %}

{% block main_area %}
<!-- Post content-->
        <div id="post-area">
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">{{post.title | lower}}</h1>
                {% if post.hook_text %}
                <h5 class="text-muted">{{post.hook_text}}</h5>
                {% endif %}
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">
                    Posted on {{post.created_at | date:"Y-m-d h:m:s"}} by {{post.author | upper}}
                </div>
                <!-- Post categories-->
                {% if post.category %}
                    <a class="badge bg-secondary text-decoration-none link-light"
                       href="{{post.category.get_absolute_url}}">
                        {{post.category}}
                    </a>
                {% else %}
                    <a class="badge bg-secondary text-decoration-none link-light"
                       href="/blog/category/no_category/">
                        미분류
                    </a>
                {% endif %}
            </header>
            {% if user.is_authenticated and user == post.author %}
                <a href="/blog/update_post/{{post.pk}}" role="button"
                    class="btn btn-info btn-sm float-right">
                <i class="fas fa-pen"> Edit Post</i>
                </a>
            {% endif %}

            <!-- Preview image figure-->
            <figure class="mb-4">
                 {% if post.head_image %}
                <img class="img-fluid rounded" src="{{post.head_image.url}}" alt="{{p.title}}의 head_image" />
                {% else %}
                <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.pk}}/800/200" alt="random image" />
                {% endif %}
            </figure>

            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">{{post.content}}</p>
                {% if post.tags.exists %}
                    <i class="fas fa-tag"></i>
                    {% for t in post.tags.iterator %}
                        <span class="badge badge-pill badge-light">
                            <a href="{{t.get_absolute_url}}">{{t}}</a>
                        </span>
                    {% endfor %}
                    <br><br>
                {% endif %}

                {% if post.file_upload %}
                <a href="{{post.file_upload.url}}" class="btn btn-outline-dark" role="button" download>
                    {% if post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                    <i class="fa-regular fa-file-excel"></i> <!--엑셀 아이콘-->
                    {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                    <i class="fa-regular fa-file-word"></i> <!--워드 아이콘-->
                    {% else %}
                    <i class="fa-regular fa-file"></i> <!--파일 아이콘-->
                    {% endif %}
                    Download {{post.get_file_name}}
                </a>
                {% endif %}
            </section>
        </div>
        <!-- Comments section-->
        <div id="comment-area" class="mb-5">
            <div class="card bg-light">
                <div class="card-body">
                    <!-- Comment form-->
                    {% if user.is_authenticated %}
                    <form class="mb-4" id="comment-form" method="post"
                        action="{{post.get_absolute_url}}new_comment/">
                        {% csrf_token %} <!--외부 침입 확인-->
                        <div class="form-group">
                            {{comment_form | crispy}}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    {% else %}
                    <a role="button" class="btn btn-dark btn-block btn-sm" href="#"
                    data-toggle="modal" data-target="#loginModal">
                    Log in and Leave a comment
                    </a>
                    {% endif %}
                    {% if post.comment_set.exists %}

                    {% for comment in post.comment_set.iterator %}
                    <!-- Single comment-->
                    <div class="media d-flex" id="comment-{{comment.pk}}">
                        <img class="mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px" />
                        <div class="media-body ms-3">
                            {% if user.is_authenticated and comment.author == user %}
                            <div class="float-right">
                                <a role="button" class="btn btn-sm btn-info"
                                    href="/blog/update_comment/{{comment.pk}}/">
                                    Edit
                                </a>
                                <a role="button" class="btn btn-sm btn-danger float-right"
                                   data-toggle="modal" data-target="#deleteModal-{{comment.pk}}"
                                   href="#">
                                    Delete
                                </a>
                            </div>
                            <!--Modal-->
                            <div class="modal fade" id="deleteModal-{{comment.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body">
                                      <del>{{comment | linebreaks}}</del>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <a role="button" class="btn btn-secondary"
                                            href="/blog/delete_comment/{{comment.pk}}/">
                                            Delete
                                        </a>
                                  </div>
                                </div>
                              </div>
                            </div>

                            {% endif %}
                            <div class="fw-bold">{{comment.author.username}}
                                <small class="text-muted">{{comment.created_at}}</small>
                            </div>
                            <p>{{comment.content | linebreaks}}</p>
                            {% if comment.created_at != comment.modified_at %}
                            <p class="text-muted float-right">
                                <small>Update : {{comment.modified_at}}</small>
                            </p>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Create Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Create a New Post</h1>
  <hr/>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}

      {{form | crispy }}
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control">
      </div>

    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
{% endblock %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    Edit Post - Blog
{% endblock %}

{% block main_area %}
  <h1>Edit Post</h1>
  <hr/>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}

      {{form|crispy}}
    <div id="div_id_tags_str">
      <label for="id_tags">Tags:</label></th>
      <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
    </div>
    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
{% endblock %}

blog/templates/blog/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <h4>{{ post.created_at }}</h4>
    <p>{{ post.content }}</p>

    <hr />
    <h3>여기에 댓글 출력</h3>
</body>
</html>